# Generated by Django 5.1.3 on 2025-01-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=100)),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(max_length=100)),
            ],
        ),
    ]
