# Generated by Django 5.1.3 on 2025-01-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task_edit_task_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='trash',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
