# Generated by Django 5.1.3 on 2025-01-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_taskimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='taskmanager.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskImages',
        ),
    ]
